from __future__ import annotations


SCHEMA_CATALOG: dict[str, dict[str, object]] = {
    "Customers": {
        "primary_key": "CustomerId",
        "columns": {
            "CustomerId": "int",
            "CustomerCode": "string",
            "CustomerName": "string",
            "Email": "string",
            "Phone": "string",
            "BillingAddress1": "string",
            "BillingCity": "string",
            "BillingCountry": "string",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
            "IsActive": "bool",
        },
        "joins": {},
    },
    "Vendors": {
        "primary_key": "VendorId",
        "columns": {
            "VendorId": "int",
            "VendorCode": "string",
            "VendorName": "string",
            "Email": "string",
            "Phone": "string",
            "AddressLine1": "string",
            "City": "string",
            "Country": "string",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
            "IsActive": "bool",
        },
        "joins": {},
    },
    "Sites": {
        "primary_key": "SiteId",
        "columns": {
            "SiteId": "int",
            "SiteCode": "string",
            "SiteName": "string",
            "AddressLine1": "string",
            "City": "string",
            "Country": "string",
            "TimeZone": "string",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
            "IsActive": "bool",
        },
        "joins": {},
    },
    "Locations": {
        "primary_key": "LocationId",
        "columns": {
            "LocationId": "int",
            "SiteId": "int",
            "LocationCode": "string",
            "LocationName": "string",
            "ParentLocationId": "int",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
            "IsActive": "bool",
        },
        "joins": {
            "SiteId": ("Sites", "SiteId"),
            "ParentLocationId": ("Locations", "LocationId"),
        },
    },
    "Items": {
        "primary_key": "ItemId",
        "columns": {
            "ItemId": "int",
            "ItemCode": "string",
            "ItemName": "string",
            "Category": "string",
            "UnitOfMeasure": "string",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
            "IsActive": "bool",
        },
        "joins": {},
    },
    "Assets": {
        "primary_key": "AssetId",
        "columns": {
            "AssetId": "int",
            "AssetTag": "string",
            "AssetName": "string",
            "SiteId": "int",
            "LocationId": "int",
            "SerialNumber": "string",
            "Category": "string",
            "Status": "string",
            "Cost": "decimal",
            "PurchaseDate": "date",
            "VendorId": "int",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
        },
        "joins": {
            "SiteId": ("Sites", "SiteId"),
            "LocationId": ("Locations", "LocationId"),
            "VendorId": ("Vendors", "VendorId"),
        },
    },
    "Bills": {
        "primary_key": "BillId",
        "columns": {
            "BillId": "int",
            "VendorId": "int",
            "BillNumber": "string",
            "BillDate": "date",
            "DueDate": "date",
            "TotalAmount": "decimal",
            "Currency": "string",
            "Status": "string",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
        },
        "joins": {
            "VendorId": ("Vendors", "VendorId"),
        },
    },
    "PurchaseOrders": {
        "primary_key": "POId",
        "columns": {
            "POId": "int",
            "PONumber": "string",
            "VendorId": "int",
            "PODate": "date",
            "Status": "string",
            "SiteId": "int",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
        },
        "joins": {
            "VendorId": ("Vendors", "VendorId"),
            "SiteId": ("Sites", "SiteId"),
        },
    },
    "PurchaseOrderLines": {
        "primary_key": "POLineId",
        "columns": {
            "POLineId": "int",
            "POId": "int",
            "LineNumber": "int",
            "ItemId": "int",
            "ItemCode": "string",
            "Description": "string",
            "Quantity": "decimal",
            "UnitPrice": "decimal",
        },
        "joins": {
            "POId": ("PurchaseOrders", "POId"),
            "ItemId": ("Items", "ItemId"),
        },
    },
    "SalesOrders": {
        "primary_key": "SOId",
        "columns": {
            "SOId": "int",
            "SONumber": "string",
            "CustomerId": "int",
            "SODate": "date",
            "Status": "string",
            "SiteId": "int",
            "CreatedAt": "datetime",
            "UpdatedAt": "datetime",
        },
        "joins": {
            "CustomerId": ("Customers", "CustomerId"),
            "SiteId": ("Sites", "SiteId"),
        },
    },
    "SalesOrderLines": {
        "primary_key": "SOLineId",
        "columns": {
            "SOLineId": "int",
            "SOId": "int",
            "LineNumber": "int",
            "ItemId": "int",
            "ItemCode": "string",
            "Description": "string",
            "Quantity": "decimal",
            "UnitPrice": "decimal",
        },
        "joins": {
            "SOId": ("SalesOrders", "SOId"),
            "ItemId": ("Items", "ItemId"),
        },
    },
    "AssetTransactions": {
        "primary_key": "AssetTxnId",
        "columns": {
            "AssetTxnId": "int",
            "AssetId": "int",
            "FromLocationId": "int",
            "ToLocationId": "int",
            "TxnType": "string",
            "Quantity": "int",
            "TxnDate": "datetime",
            "Note": "string",
        },
        "joins": {
            "AssetId": ("Assets", "AssetId"),
            "FromLocationId": ("Locations", "LocationId"),
            "ToLocationId": ("Locations", "LocationId"),
        },
    },
}
